using RaphCare.Client.Contracts;
using RaphCare.Client.Models;

namespace RaphCare.Client.Contracts.Interfaces;

public interface IAdminClinicService
{
    Task<Response<IReadOnlyList<ClinicListItem>>> GetClinicsAsync(CancellationToken cancellationToken = default);
    Task<Response<ClinicDetail>> GetClinicAsync(Guid clinicId, CancellationToken cancellationToken = default);
    Task<Response<ClinicDetail>> UpdateClinicAsync(Guid clinicId, UpdateClinicRequest request, CancellationToken cancellationToken = default);
    Task<Response<PagedClinicPatients>> GetPatientsAsync(Guid clinicId, int pageNumber = 1, int pageSize = 20, string? search = null, CancellationToken cancellationToken = default);
    Task<Response<ClinicPatientDetail>> GetPatientDetailAsync(Guid clinicId, Guid patientId, CancellationToken cancellationToken = default);
    Task<Response<ClinicPatientPhoto?>> GetPatientPhotoAsync(Guid clinicId, Guid patientId, CancellationToken cancellationToken = default);
    Task<Response<ClinicPatientListItem>> GrantPatientAccessAsync(Guid clinicId, string email, string? notes = null, CancellationToken cancellationToken = default);
    Task<Response<bool>> EnsureMembershipAsync(Guid clinicId, CancellationToken cancellationToken = default);
    Task<Response<Guid?>> ClaimByRegistrationNumberAsync(string registrationNumber, CancellationToken cancellationToken = default);
    Task<Response<RegisterClinicResult>> RegisterClinicAsync(RegisterClinicRequest request, CancellationToken cancellationToken = default);
    Task<Response<IReadOnlyList<ClinicStaffMember>>> GetStaffAsync(Guid clinicId, CancellationToken cancellationToken = default);
    Task<Response<ClinicStaffMember>> InviteStaffAsync(Guid clinicId, string email, string? jobRole = null, CancellationToken cancellationToken = default);
    Task<Response<bool>> ResendStaffInvitationAsync(Guid clinicId, Guid userId, CancellationToken cancellationToken = default);
    Task<Response<bool>> ResendPendingInvitationAsync(Guid clinicId, Guid invitationId, CancellationToken cancellationToken = default);
    Task<Response<bool>> CancelPendingInvitationAsync(Guid clinicId, Guid invitationId, CancellationToken cancellationToken = default);
    Task<Response<bool>> RemoveStaffAsync(Guid clinicId, Guid userId, CancellationToken cancellationToken = default);
    Task<Response<bool>> UpdateStaffRoleAsync(Guid clinicId, Guid userId, bool isAdministrator, string? jobRole = null, CancellationToken cancellationToken = default);
    Task<Response<FacilityListItem>> CreateFacilityAsync(Guid clinicId, SaveFacilityRequest request, CancellationToken cancellationToken = default);
    Task<Response<FacilityListItem>> UpdateFacilityAsync(Guid clinicId, Guid facilityId, SaveFacilityRequest request, CancellationToken cancellationToken = default);
    Task<Response<bool>> DeleteFacilityAsync(Guid clinicId, Guid facilityId, CancellationToken cancellationToken = default);
    Task<Response<ClinicDashboard>> GetDashboardAsync(Guid clinicId, CancellationToken cancellationToken = default);
    Task<Response<IReadOnlyList<ClinicProviderListItem>>> GetProvidersAsync(Guid clinicId, CancellationToken cancellationToken = default);
    Task<Response<ClinicProviderDetail>> GetProviderDetailAsync(Guid clinicId, Guid providerId, CancellationToken cancellationToken = default);
    Task<Response<ClinicProviderListItem>> CreateProviderAsync(Guid clinicId, Guid userId, string? licenseNumber = null, CancellationToken cancellationToken = default);
    Task<Response<bool>> SetProviderActiveAsync(Guid clinicId, Guid providerId, bool isActive, CancellationToken cancellationToken = default);
    Task<Response<ClinicProviderSchedule>> CreateProviderScheduleAsync(Guid clinicId, Guid providerId, CreateProviderScheduleRequest request, CancellationToken cancellationToken = default);
    Task<Response<bool>> DeleteProviderScheduleAsync(Guid clinicId, Guid providerId, Guid scheduleId, CancellationToken cancellationToken = default);
    Task<Response<PagedClinicAppointments>> GetAppointmentsAsync(Guid clinicId, int pageNumber = 1, int pageSize = 20, DateTime? fromUtc = null, DateTime? toUtc = null, string? status = null, CancellationToken cancellationToken = default);
    Task<Response<ClinicAppointmentListItem>> BookAppointmentAsync(Guid clinicId, BookClinicAppointmentRequest request, CancellationToken cancellationToken = default);
    Task<Response<bool>> CancelAppointmentAsync(Guid clinicId, Guid appointmentId, CancellationToken cancellationToken = default);
    Task<Response<ClinicAppointmentListItem>> RescheduleAppointmentAsync(Guid clinicId, Guid appointmentId, RescheduleClinicAppointmentRequest request, CancellationToken cancellationToken = default);
    Task<Response<ClinicVisitDetail>> StartVisitAsync(Guid clinicId, Guid appointmentId, string? summary = null, CancellationToken cancellationToken = default);
    Task<Response<ClinicVisitDetail>> GetVisitAsync(Guid clinicId, Guid visitId, CancellationToken cancellationToken = default);
    Task<Response<ClinicVisitDetail>> CompleteVisitAsync(Guid clinicId, Guid visitId, string? summary = null, CancellationToken cancellationToken = default);
    Task<Response<ClinicVisitVital>> RecordVisitVitalAsync(Guid clinicId, Guid visitId, RecordVisitVitalRequest request, CancellationToken cancellationToken = default);
    Task<Response<ClinicVisitSoapNote>> SaveVisitSoapNoteAsync(Guid clinicId, Guid visitId, SaveVisitSoapNoteRequest request, CancellationToken cancellationToken = default);
    Task<Response<ClinicVisitNote>> AddVisitNoteAsync(Guid clinicId, Guid visitId, AddVisitNoteRequest request, CancellationToken cancellationToken = default);
    Task<Response<ClinicVisitPrescription>> AddVisitPrescriptionAsync(Guid clinicId, Guid visitId, AddVisitPrescriptionRequest request, CancellationToken cancellationToken = default);
    Task<Response<ClinicVisitLabResult>> AddVisitLabResultAsync(Guid clinicId, Guid visitId, AddVisitLabResultRequest request, CancellationToken cancellationToken = default);
    Task<Response<ClinicVisitLabResult>> CompleteLabOrderAsync(Guid clinicId, Guid labRequestId, CompleteVisitLabOrderRequest request, CancellationToken cancellationToken = default);
    Task<Response<ClinicVisitPrescription>> DispensePrescriptionAsync(Guid clinicId, Guid prescriptionId, CancellationToken cancellationToken = default);
    Task<Response<ClinicVisitPrescription>> CancelPrescriptionAsync(Guid clinicId, Guid prescriptionId, CancellationToken cancellationToken = default);
    Task<Response<ClinicVisitPrescription>> UndoPrescriptionAsync(Guid clinicId, Guid prescriptionId, CancellationToken cancellationToken = default);
    Task<Response<ClinicVisitLabResult>> CancelLabOrderAsync(Guid clinicId, Guid labRequestId, CancellationToken cancellationToken = default);
    Task<Response<ClinicVisitLabResult>> UndoLabOrderAsync(Guid clinicId, Guid labRequestId, CancellationToken cancellationToken = default);
    Task<Response<ClinicVisitPrescription>> CallPrescriptionAsync(Guid clinicId, Guid prescriptionId, CancellationToken cancellationToken = default);
    Task<Response<ClinicVisitLabResult>> CallLabOrderAsync(Guid clinicId, Guid labRequestId, CancellationToken cancellationToken = default);
    Task<Response<string>> EnsureCollectionDisplayTokenAsync(Guid clinicId, CancellationToken cancellationToken = default);
    Task<Response<ClinicCollectionBoard>> GetCollectionOrdersAsync(Guid clinicId, string? search = null, CancellationToken cancellationToken = default);
    Task<Response<ClinicCasualtyBoard>> GetCasualtyBoardAsync(Guid clinicId, CancellationToken cancellationToken = default);
    Task<Response<ClinicCasualtyTicket>> CreateCasualtyTicketAsync(Guid clinicId, CreateCasualtyTicketRequest request, CancellationToken cancellationToken = default);
    Task<Response<ClinicCasualtyTicket>> CallCasualtyTicketAsync(Guid clinicId, Guid ticketId, CancellationToken cancellationToken = default);
    Task<Response<ClinicCasualtyTicket>> CompleteCasualtyTicketAsync(Guid clinicId, Guid ticketId, bool cancel = false, CancellationToken cancellationToken = default);
    Task<Response<string>> EnsureCasualtyDisplayTokenAsync(Guid clinicId, CancellationToken cancellationToken = default);
    Task<Response<ClinicTheatreBoard>> GetTheatreBoardAsync(Guid clinicId, DateTime? dayUtc = null, CancellationToken cancellationToken = default);
    Task<Response<ClinicTheatreCase>> CreateTheatreCaseAsync(Guid clinicId, CreateTheatreCaseRequest request, CancellationToken cancellationToken = default);
    Task<Response<ClinicTheatreCase>> UpdateTheatreCaseStatusAsync(Guid clinicId, Guid caseId, string status, CancellationToken cancellationToken = default);
    Task<Response<ClinicReferralBoard>> GetReferralBoardAsync(Guid clinicId, CancellationToken cancellationToken = default);
    Task<Response<ClinicReferral>> CreateReferralAsync(Guid clinicId, CreateReferralRequest request, CancellationToken cancellationToken = default);
    Task<Response<ClinicReferral>> UpdateReferralStatusAsync(Guid clinicId, Guid referralId, string status, CancellationToken cancellationToken = default);
    Task<Response<ClinicRosterBoard>> GetRosterBoardAsync(Guid clinicId, DateTime? dayUtc = null, CancellationToken cancellationToken = default);
    Task<Response<ClinicRosterEntry>> CreateRosterEntryAsync(Guid clinicId, CreateRosterEntryRequest request, CancellationToken cancellationToken = default);
    Task<Response<bool>> DeleteRosterEntryAsync(Guid clinicId, Guid entryId, CancellationToken cancellationToken = default);
    Task<Response<IReadOnlyList<ClinicDeviceListItem>>> GetDevicesAsync(Guid clinicId, CancellationToken cancellationToken = default);
    Task<Response<ClinicInpatientBoard>> GetInpatientBoardAsync(Guid clinicId, CancellationToken cancellationToken = default);
    Task<Response<ClinicWard>> CreateWardAsync(Guid clinicId, CreateWardRequest request, CancellationToken cancellationToken = default);
    Task<Response<ClinicWard>> UpdateWardAsync(Guid clinicId, Guid wardId, UpdateWardRequest request, CancellationToken cancellationToken = default);
    Task<Response<bool>> DeleteWardAsync(Guid clinicId, Guid wardId, CancellationToken cancellationToken = default);
    Task<Response<ClinicRoom>> CreateRoomAsync(Guid clinicId, CreateRoomRequest request, CancellationToken cancellationToken = default);
    Task<Response<ClinicRoom>> UpdateRoomAsync(Guid clinicId, Guid roomId, UpdateRoomRequest request, CancellationToken cancellationToken = default);
    Task<Response<bool>> DeleteRoomAsync(Guid clinicId, Guid roomId, CancellationToken cancellationToken = default);
    Task<Response<ClinicBed>> CreateBedAsync(Guid clinicId, CreateBedRequest request, CancellationToken cancellationToken = default);
    Task<Response<ClinicBed>> UpdateBedAsync(Guid clinicId, Guid bedId, UpdateBedRequest request, CancellationToken cancellationToken = default);
    Task<Response<ClinicBed>> SetBedStatusAsync(Guid clinicId, Guid bedId, string status, CancellationToken cancellationToken = default);
    Task<Response<bool>> DeleteBedAsync(Guid clinicId, Guid bedId, CancellationToken cancellationToken = default);
    Task<Response<ClinicAdmission>> AdmitPatientAsync(Guid clinicId, AdmitPatientRequest request, CancellationToken cancellationToken = default);
    Task<Response<ClinicAdmission>> DischargeAdmissionAsync(Guid clinicId, Guid admissionId, DischargeAdmissionRequest request, CancellationToken cancellationToken = default);
    Task<Response<string>> DraftDischargeSummaryAsync(Guid clinicId, Guid admissionId, CancellationToken cancellationToken = default);
    Task<Response<IReadOnlyList<ClinicAdmissionObservation>>> GetAdmissionObservationsAsync(Guid clinicId, Guid admissionId, CancellationToken cancellationToken = default);
    Task<Response<ClinicAdmissionObservation>> AddAdmissionObservationAsync(Guid clinicId, Guid admissionId, AddAdmissionObservationRequest request, CancellationToken cancellationToken = default);
    Task<Response<ClinicAdmission>> TransferAdmissionAsync(Guid clinicId, Guid admissionId, TransferAdmissionRequest request, CancellationToken cancellationToken = default);
    Task<Response<PagedClinicAdmissions>> GetAdmissionsAsync(Guid clinicId, int pageNumber = 1, int pageSize = 20, string? status = null, CancellationToken cancellationToken = default);
    Task<Response<ClinicAdmission>> GetAdmissionByIdAsync(Guid clinicId, Guid admissionId, CancellationToken cancellationToken = default);
    Task<Response<ClinicTeleJoinInfo>> StartTeleSessionAsync(Guid clinicId, Guid appointmentId, CancellationToken cancellationToken = default);
    Task<Response<bool>> RevokePatientAccessAsync(Guid clinicId, Guid patientId, CancellationToken cancellationToken = default);
}
