namespace RaphCare.Application.Common.Configuration;

/// <summary>Host configuration for the patient AI assistant (<c>PatientAssistant</c> section).</summary>
public sealed class PatientAssistantAiOptions
{
    public const string SectionName = "PatientAssistant";

    /// <summary>Shown with every response; not generated by an external model in the placeholder implementation.</summary>
    public string MedicalDisclaimer { get; set; } =
        "This assistant is not a substitute for professional medical advice, diagnosis, or treatment. For urgent concerns, contact your clinician or local emergency services.";

    /// <summary>Placeholder reply when no LLM is configured; must stay non-diagnostic.</summary>
    public string PlaceholderReply { get; set; } =
        "Thanks for your message. A full AI assistant is not connected in this environment yet. Use this space for general wellness questions only, never for emergencies, and always follow your care team's guidance.";

    /// <summary>Default chat deployment: cheapest pay-as-you-go GPT-4.1 mini on Azure OpenAI.</summary>
    public const string DefaultDeploymentName = "gpt-4.1-mini";

    /// <summary>REST api-version that gpt-4.1-mini chat completions accept.</summary>
    public const string DefaultApiVersion = "2024-08-01-preview";

    /// <summary>Azure OpenAI resource endpoint, e.g. <c>https://your-resource.openai.azure.com/</c>.</summary>
    public string? AzureOpenAiEndpoint { get; set; }

    /// <summary>Azure OpenAI API key (prefer Key Vault / environment in production).</summary>
    public string? AzureOpenAiApiKey { get; set; }

    /// <summary>Deployment name for the chat model. Defaults to <see cref="DefaultDeploymentName"/>.</summary>
    public string? AzureOpenAiDeployment { get; set; } = DefaultDeploymentName;

    /// <summary>API version query string, e.g. <c>2024-08-01-preview</c>.</summary>
    public string AzureOpenAiApiVersion { get; set; } = DefaultApiVersion;

    /// <summary>Optional override for the system prompt; otherwise a safe default is used.</summary>
    public string? SystemPrompt { get; set; }

    /// <summary>Max completion tokens for the assistant reply.</summary>
    public int MaxCompletionTokens { get; set; } = 512;

    /// <summary>Sampling temperature for chat completions.</summary>
    public double Temperature { get; set; } = 0.5;

    /// <summary>
    /// Max earlier user/assistant turns sent with the current message (cost window). Default 8.
    /// </summary>
    public int MaxPriorMessages { get; set; } = 8;

    /// <summary>True when Azure OpenAI chat can be called.</summary>
    public bool IsAzureOpenAiConfigured =>
        !string.IsNullOrWhiteSpace(AzureOpenAiEndpoint)
        && !string.IsNullOrWhiteSpace(AzureOpenAiApiKey)
        && !string.IsNullOrWhiteSpace(AzureOpenAiDeployment);
}
