namespace RaphCare.Application.Common.Configuration;

/// <summary>Host configuration for the patient AI assistant (<c>PatientAssistant</c> section).</summary>
public sealed class PatientAssistantAiOptions
{
    public const string SectionName = "PatientAssistant";

    /// <summary>Shown with every response; not generated by an external model in the placeholder implementation.</summary>
    public string MedicalDisclaimer { get; set; } =
        "This assistant is not a substitute for professional medical advice, diagnosis, or treatment. For urgent concerns, contact your clinician or local emergency services.";

    /// <summary>Placeholder reply when no LLM is configured; must stay non-diagnostic.</summary>
    public string PlaceholderReply { get; set; } =
        "Thanks for your message. A full AI assistant is not connected in this environment yet. Use this space for general wellness questions only—never for emergencies—and always follow your care team's guidance.";
}
