// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaphCare.Persistence;

#nullable disable

namespace RaphCare.Persistence.Migrations.DeviceDb
{
    [DbContext(typeof(DeviceDbContext))]
    partial class DeviceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RaphCare.Domain.Devices.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("BluetoothMacAddress")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeviceFirmwareId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceManufacturerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAssigned")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("BluetoothMacAddress")
                        .IsUnique()
                        .HasFilter("[BluetoothMacAddress] IS NOT NULL");

                    b.HasIndex("DeviceFirmwareId");

                    b.HasIndex("DeviceManufacturerId");

                    b.HasIndex("DeviceTypeId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("RaphCare.Domain.Devices.DeviceAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("DeviceAssignments");
                });

            modelBuilder.Entity("RaphCare.Domain.Devices.DeviceEmergencyEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaregiverNotificationSummary")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("CaregiversNotified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CaregiversNotifiedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ExternalCorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<double?>("HorizontalAccuracyMeters")
                        .HasColumnType("float");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("PatientId");

                    b.HasIndex("DeviceId", "ExternalCorrelationId")
                        .IsUnique()
                        .HasFilter("[ExternalCorrelationId] IS NOT NULL");

                    b.ToTable("DeviceEmergencyEvents", (string)null);
                });

            modelBuilder.Entity("RaphCare.Domain.Devices.DeviceFirmware", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ReleasedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("DeviceFirmwares");
                });

            modelBuilder.Entity("RaphCare.Domain.Devices.DeviceManufacturer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SupportContact")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DeviceManufacturers");
                });

            modelBuilder.Entity("RaphCare.Domain.Devices.DeviceReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("bit");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PrimaryValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReadingType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("PatientId");

                    b.HasIndex("RecordedAt");

                    b.ToTable("DeviceReadings", (string)null);

                    b.HasDiscriminator().HasValue("DeviceReading");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RaphCare.Domain.Devices.DeviceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DeviceTypes");
                });

            modelBuilder.Entity("RaphCare.Domain.Devices.BloodPressureReading", b =>
                {
                    b.HasBaseType("RaphCare.Domain.Devices.DeviceReading");

                    b.Property<decimal>("Diastolic")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Systolic")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("BloodPressure");
                });

            modelBuilder.Entity("RaphCare.Domain.Devices.ECGReading", b =>
                {
                    b.HasBaseType("RaphCare.Domain.Devices.DeviceReading");

                    b.Property<decimal>("HeartRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RhythmClassification")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasDiscriminator().HasValue("ECG");
                });

            modelBuilder.Entity("RaphCare.Domain.Devices.GlucoseReading", b =>
                {
                    b.HasBaseType("RaphCare.Domain.Devices.DeviceReading");

                    b.Property<decimal>("GlucoseLevel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsFasting")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Glucose");
                });

            modelBuilder.Entity("RaphCare.Domain.Devices.HeartRateReading", b =>
                {
                    b.HasBaseType("RaphCare.Domain.Devices.DeviceReading");

                    b.Property<decimal>("HeartRate")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("DeviceReadings", t =>
                        {
                            t.Property("HeartRate")
                                .HasColumnName("HeartRateReading_HeartRate");
                        });

                    b.HasDiscriminator().HasValue("HeartRate");
                });

            modelBuilder.Entity("RaphCare.Domain.Devices.PulseOximeterReading", b =>
                {
                    b.HasBaseType("RaphCare.Domain.Devices.DeviceReading");

                    b.Property<decimal>("PulseRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SpO2")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("PulseOximeter");
                });

            modelBuilder.Entity("RaphCare.Domain.Devices.WeightReading", b =>
                {
                    b.HasBaseType("RaphCare.Domain.Devices.DeviceReading");

                    b.Property<decimal?>("BMI")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("Weight");
                });

            modelBuilder.Entity("RaphCare.Domain.Devices.Device", b =>
                {
                    b.HasOne("RaphCare.Domain.Devices.DeviceFirmware", "DeviceFirmware")
                        .WithMany()
                        .HasForeignKey("DeviceFirmwareId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RaphCare.Domain.Devices.DeviceManufacturer", "DeviceManufacturer")
                        .WithMany()
                        .HasForeignKey("DeviceManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaphCare.Domain.Devices.DeviceType", "DeviceType")
                        .WithMany()
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeviceFirmware");

                    b.Navigation("DeviceManufacturer");

                    b.Navigation("DeviceType");
                });

            modelBuilder.Entity("RaphCare.Domain.Devices.DeviceAssignment", b =>
                {
                    b.HasOne("RaphCare.Domain.Devices.Device", "Device")
                        .WithMany("DeviceAssignments")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("RaphCare.Domain.Devices.DeviceEmergencyEvent", b =>
                {
                    b.HasOne("RaphCare.Domain.Devices.Device", "Device")
                        .WithMany("DeviceEmergencyEvents")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("RaphCare.Domain.Devices.DeviceReading", b =>
                {
                    b.HasOne("RaphCare.Domain.Devices.Device", "Device")
                        .WithMany("DeviceReadings")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("RaphCare.Domain.Devices.Device", b =>
                {
                    b.Navigation("DeviceAssignments");

                    b.Navigation("DeviceEmergencyEvents");

                    b.Navigation("DeviceReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
